#spring.application.name=taco-cloud
spring:
    application:
        name: taco-cloud
    jpa:
            database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true



#spring.datasource.generate-unique-name=false
#spring.datasource.name=tacoCloud
    datasource:
        generate-unique-name: false
        name: tacoCloud
        url: jdbc:h2:mem:tacocloud
        driver-class-name: org.h2.Driver
        username: sa
        password: ""

        #consequently, the database URL will be "jdbc:h2_mem:tacocloud"

