##spring.application.name=taco-cloud
#spring:
#    applicacion:
#        name: taco-cloud
#        
#
#
#
##spring.datasource.generate-unique-name=false
##spring.datasource.name=tacoCloud
#    datasource:
#        ganerate-unique-name: false
#        name: tacoCloud
#        
#        #consequently, the database URL will be "jdbc:h2_mem:tacocloud"


spring:
  application:
    name: taco-cloud

  datasource:
    generate-unique-name: false
    name: tacoCloud
    url: jdbc:h2:mem:tacoCloud
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console